### ISSUE TITLE
trouble using in iOS app

### ISSUE THREAD

**Issue by misterinterrupt** [moosefactory/SwiftMIDI#2]
Hello, I am trying to use spm to use this lib.. running into issues.

1. is the library currently in a state to use in iOS 14 ?
2. can you help me to figure out the problem?

thanks!

**Comment by moosefactory** [comment]
Hi @misterinterrupt 

I'm so sorry I have not noticed this before. I have unsubscribed to all the projects I was following, because it was too much noise. And there I found a message on one of my projects! 

I would be glad to have at least one more user than myself, but I'm afraid it still needs some work.

I did not try it on iOS 14, only on MacOS. But it should work, since it is only a wrapper. The only logic I add is the 'MidiFilter', but it is not totally ready yet. And I'm not sure I will keep it in this framework.

Sorry again mister interrupt ;)

**Comment by moosefactory** [comment]
I will do some tests on iOS when I find the time. I'am actually over-busy on a drum machine app for Mac

**Comment by moosefactory** [comment]
From your profile, I have been on the Electro-Smith site. I did not knew. That's great! Then from their video, I have followed a link to Delia Derbyshire who composed the Doctor Who theme with only tapes and rudimentary electronic machines. The YouTube syndrome.. I have lost more than one hour. Thanks for that.

**Comment by misterinterrupt** [comment]
hey i feel you, msg noise like crazy. 

ill watch this space in case of updates.

can't wait to see the drum machine!

:) I'm glad you found a good distraction because of me 
Daisy is really cool
cheers!

**Comment by moosefactory** [comment]
I'll probably need some beta testers.. Even better if I can collaborate with other developers.
The project needs a bit more definition, but it's already quite cool and I use it to make some songs. For now it only control external gears. I've made few experiments with audio units, but it's too much work for me right now. I focus on the rhythmic and the edition.

![Screenshot 2021-04-06 at 20 23 48](https://user-images.githubusercontent.com/1597378/113760011-0a21e400-9716-11eb-8f1e-12286edb7c38.png)
